### ISSUE TITLE
App markup

### ISSUE THREAD

**Issue by okhy** [okhy/ERM#8]
#### Task passing requirements:
- [x] Markup is done with React Components
- [x] Use ErrorBoundary component for catching and displaying errors 
- [x] Use smart/dumb components approach
- [x] 100% decomposition ( evaluated by mentor )
--- 
#### Own tasks / notes:
- [x] Use controlled input for smart request sending / validation / result suggestions

**Comment by okhy** [comment]
- [ ] Use controlled input for smart request sending / validation / result suggestions
